### ISSUE TITLE
Pagination menu is broken when the number of pages is between 4 and 5

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact-frontend#215]
![Preview](https://user-images.githubusercontent.com/1556356/46507568-6cde5000-c839-11e8-85b5-5e0e4724c523.png)
![selection_018](https://user-images.githubusercontent.com/1556356/46507672-fee65880-c839-11e8-82c2-b87b3d5235a1.png)

**Comment by FrancoisChastel** [comment]
By the way it's look like there is a displaying problem as well, you can see that the different page numbers are not aligned anymore.
