### ISSUE TITLE
Next page nav button is disabled on https://captainfact.io/videos

### ISSUE THREAD

**Issue by julien-leclercq** [CaptainFact/captain-fact-frontend#306]
The next page nav button is disabled whereas I am on the videos first page and there are obviously more videos to show.

Other users don't have the problem and I don't have neither when I am in private browsing.

**To Reproduce**
1. Go to https://captainfact.io
2. Click on the videos icon in the side menu
3. the next page button is disabled

**Screenshots**
<img width="1440" alt="capture d ecran 2018-12-07 a 15 00 43" src="https://user-images.githubusercontent.com/9319408/49652417-4a7fd300-fa32-11e8-8915-cef0ca670dca.png">
<img width="1440" alt="capture d ecran 2018-12-07 a 15 08 47" src="https://user-images.githubusercontent.com/9319408/49652444-59ff1c00-fa32-11e8-8d82-7f0fc63bddd2.png">

**System:**
 - Mac OS mojave
 - chrome 
 - Version 70.0.3538.110
 - uBlock origin

**Comment by Betree** [comment]
First clue is that you have only community-submitted videos here. What happens if you try changing this filter? A `localStorage.clear()` will probably solve the problem.

**Comment by julien-leclercq** [comment]
it works :)

**Comment by Betree** [comment]
Ok great! But that means I may have made a dirty state migration. Hard to say if other users may be impacted, I'll be careful with that.
