### ISSUE TITLE
Discord link on homepage is wrong

### ISSUE THREAD

**Issue by nazmifr** [CaptainFact/captain-fact-frontend#567]
Hi,
Just noticed this link here:
![image](https://user-images.githubusercontent.com/9401751/69493754-de041b00-0eb2-11ea-8e9e-89e212a117c9.png)
is redirecting to github and not discord, I can't seem to find the file for the index on the site so I raise this issue instead of sending a pull request.

Best regards and thanks for your work!

**Comment by Miragide** [comment]
Thanks you!
https://github.com/CaptainFact/captain-fact-frontend/pull/568
